language: go
sudo: false
go:
    - 1.8
branches:
  only:
  - master
  - hotfix
  - release
  - develop
  - /feature.*/
before_install:
  - sudo apt-get update
  - sudo apt-get install -o Dpkg::Options::="--force-confold" --force-yes -y docker-engine
  - make package-deps
  - make deps
before_script:
script:
  - make lint
  - make test
  - make build
notifications:
after_success:
  - make package
  - make upload-release
